name: build LeanCreator on all platforms
on: [push]
jobs:
  build-on-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-multilib
          sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libxcb1-dev
	
